title: Muhammad Arsath K F # your name (or website title) here
logo: "/images/arsathgithub.jpg?raw=true" # your photo (or logo) here
description:  # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.cse.iitm.ac.in/profile.php?arg=MTY1OQ==">Research Scholar at Indian Institute of Technology, Madras</a>
  <br><br>
  <a href="https://www.linkedin.com/in/muhammadarsath/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-147142621-1 # your Google Analytics tracking ID here

